### ISSUE TITLE
Unlock button not showing

### ISSUE THREAD

**Issue by SerhiiZahuba** [ltb-project/service-desk#100]
In AD, the user is blocked because the password was entered incorrectly. But on the interface I don't see a button to unlock it. Please help. thank you

![image](https://github.com/ltb-project/service-desk/assets/36307887/b476d884-4154-405f-971c-78abde992bfa)

**Comment by coudot** [comment]
Service Desk is not compatible with AD. See https://github.com/ltb-project/service-desk/issues/52
