### ISSUE TITLE
LDAP - Bind error 49  (Invalid credentials) since upgrade on pw change

### ISSUE THREAD

**Issue by optikkore** [ltb-project/service-desk#101]
Ever since the 5.0 upgrade despite giving a success message service desk does not change the password and throws this error in sd_error.log 

LDAP - Bind error 49  (Invalid credentials), referer: https://<url redacted>/index.php?page=display&dn=<DN redacted>&resetpasswordresult=passwordchanged

no config has changed, we use the Self-Service Portal and that works just fine same user,  nearly everything config-wise is the same.

M$ Active Directory btw, I can't seem to figure out how to troubleshoot this, event viewer filtered for LDAP error event doesn't show anything relevant either

**Comment by coudot** [comment]
Service Desk is not compatible with Active Directory, see #48
