### ISSUE TITLE
Reset password with success message but password still the old password

### ISSUE THREAD

**Issue by MessaoudDIF** [ltb-project/service-desk#105]
Hi, 
We have configured a Domain Controller with LDAPS (password complexity is disabled), reading information is done correctly:

- If "Force reset at next connection" is set to "No", then, we receive success message and the "update date" is updated, but the password is not updated, the old password still work.
`"action":"resetpassword","result":"passwordchanged"`

- If we set "Force reset at next connection" to "Yes" we receve : Password was refused.
`"action":"resetpassword","result":"passwordrefused"`

- Search & Password check work fine
`"action":"checkpassword","result":"passwordok"`

WindowsServer 2012 / RH8 Apache & PHP 8.0
Any suggestions ?

**Comment by coudot** [comment]
See #52, Service Desk is not compatible with Active Directory
