### ISSUE TITLE
Constant FILTER_SANITIZE_STRING is deprecated

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#106]
Hi everyone,

I upgraded to SD 0.5.1
and a warning about a deprecated feature is is now displayed

![image](https://github.com/ltb-project/service-desk/assets/77276760/0982ef07-1e36-4afe-9e33-ae0e71fc6f6e)

Cheers

**Comment by coudot** [comment]
Hello @cmaudoux you can test the patch proposed in #107 

That said, in production we generally don't display errors on the website and ignore the deprecated warning messages. Set this in php.ini:
```ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
```

You will still be able to see errors messages in logs.

**Comment by cmaudoux** [comment]
Hi @coudot 

It is OK for me .
Thx !
