### ISSUE TITLE
Display localized time

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/service-desk#110]
Currently, when an account is locked, we display the time stored in pwdAccountLockedTime.
For example:

```
pwdAccountLockedTime: 20231124084929Z
```
Self Service password displays:

```
Automatic unlock date: 25/11/2023 - 08:49:29 (UTC)
```

We could have an option to display localized time: 25/11/2023 - 09:49:29

**Comment by coudot** [comment]
The time format can be configured with `$date_specifiers`: https://service-desk.readthedocs.io/en/stable/general-parameters.html#dates

So you can easily display the UTC information

We should indeed add a feature to change the time zone

**Comment by davidcoutadeur** [comment]
Seems the date is already configured to display the timezone, but it is not working:

```
<p>{$msg_unlockdate} {$unlockDate|date_format:{$date_specifiers}}</p>
```

**Comment by coudot** [comment]
To change time zone: https://github.com/ltb-project/service-desk/blob/master/lib/date.inc.php#L68C20-L68C20

**Comment by coudot** [comment]
https://www.smarty.net/docsv2/fr/language.modifier.date.format.tpl

**Comment by davidcoutadeur** [comment]
The date_specifiers was overload somewhere. Sorry for the noise.

I keep the issue opened for the new feature to display localized time, which could be interesting IMO.

**Comment by davidcoutadeur** [comment]
Should be ok with #111
