### ISSUE TITLE
Carriage return before Signature

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#113]
Hi,

When an email is sent, signature is apppended to the body.

Exemple below with signature = Cnau PN
"""
Bonjour,

Le mot de passe du compte uid=173668,ou=personnes,dc=gendarmerie,dc=interieur,dc=gouv,dc=fr a été changé.Cnau PN
"""

**Comment by coudot** [comment]
You can simply configure mail_signature like this:
```php
$mail_signature = "\n\nCnau PN";
