### ISSUE TITLE
Tip for integrating with active directory

### ISSUE THREAD

**Issue by EUrubatan** [ltb-project/service-desk#114]
I believe it can help
https://ldaprecord.com/

**Comment by EUrubatan** [comment]
https://ldaprecord.com/docs/core/v3/active-directory/users#creation

**Comment by coudot** [comment]
Thanks for the tip, but we are already working on a LDAP Lib (https://github.com/ltb-project/ltb-ldap) and I would like to avoid depending on too much components.
