### ISSUE TITLE
Displayed message if wrong a password is tested is not really explicit

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#117]
Hi,

Enable use_checkpassword option.

1/ If you test a good password displayed message is " Authentification réussie ! " but in warning mode (red).
It works but message suggests an error... It could be yellow or green.

![image](https://github.com/ltb-project/service-desk/assets/77276760/99e0c3b0-c19a-42cd-8d7b-e196b1166d10)

2/ If you test a wrong password displayed message is "  Erreur de communication avec l'annuaire LDAP " .
In this case message suggests an error with LDAP... Message could be "Wrong credential" or "Bad password".

![image](https://github.com/ltb-project/service-desk/assets/77276760/360b66bb-2d7b-4ae4-b258-748fcd13ab50)

Cheers

**Comment by coudot** [comment]
I don't reproduce your issue.

You should stay on the same page when testing the password.

With a wrong password :

![image](https://github.com/ltb-project/service-desk/assets/883396/72cb8615-c343-463f-adc3-929e22b53180)

With a good password : 

![image](https://github.com/ltb-project/service-desk/assets/883396/ddc30ac2-e3f9-431b-891b-760064eeabeb)

**Comment by cmaudoux** [comment]
Thanks for your tests and reply.

Issue may be due to our LoadBalancer.

**Comment by cmaudoux** [comment]
Hello,

Issue linked to issue #106
