### ISSUE TITLE
Display password policy when changing password

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#119]
Hello,

Append options to be able to display password policy like user infos when  changing password.

**Comment by coudot** [comment]
Hello @cmaudoux 

do you want to know which ppolicy is associated to user? (See https://github.com/ltb-project/service-desk/issues/53)

Or do you want to display all parameters of LDAP ppolicy ?

Note that there is no local ppolicy in Service Desk (for now)

**Comment by cmaudoux** [comment]
Hello,

I just want to display LDAP policy parameters :wink:

**Comment by coudot** [comment]
The plan for this feature:
* Add local password policy settings
* Move password policy check component form Self Service Password to LTB PHP common lib
* Displya thee password check component in password reset box in Service Desk
