### ISSUE TITLE
Check password in history of old passwords

### ISSUE THREAD

**Issue by coudot** [ltb-project/service-desk#126]
Currently, we check the password on the current value (by doing an LDAP BIND)

We would like to be able to browse password history and check the password on this history.

Use case : the password of the user has changed but the user forgot it and use an old password. We can verify that this old password is really a previous password of the user.

It would be possible only with a standard LDAP directory that is compatible with password policy (pwdHistory)

**Comment by coudot** [comment]
Prerequisite : #118

**Comment by coudot** [comment]
This is not what is wanted here.

The big plan is:
* Update the code only for the check password feature
* Read the password history attribute (pwdHistory in OpenLDAP)
* For each value of password history, get the hashed password (with the salt if needed)
* Do the same hash function (with same salt if needed) on the checked password
* If both values match, then it means the password is in the password history

**Comment by davidcoutadeur** [comment]
Hello,

@abpai94 I think this issue was assigned to me at the beginning. Did you have a special reason for working on this?

I have no problem for you to work on this issue, but:

1. please take care to communicate before auto-assigning (in order for us to share and plan the tasks the best we can)
2. I had a precise idea of how to deal with this issue, so if you have to work on it, I could at least give you the implementation details.

David

**Comment by abpai94** [comment]
Hey @davidcoutadeur 

Apologies for not informing you before picking it up. I found the topic interesting so I picked it up. In the future I will make sure to mention to the previously assigned person before picking up their ticket.

As you can see in the pull request I went down a very specific rabbit hole which proved to be incorrect. I have spoken to @coudot who provided me more context which I will implement. So any more information you have about implementations would be helpful.

Abhishek

**Comment by abpai94** [comment]
@coudot The issue has been completed. It requires the ltb-project/ltb-common#31 to be merged and the new version incremented for this feature to work.

**Comment by davidcoutadeur** [comment]
I'll give a look to this feature on tomorrow.

@abpai94 : if the feature is finished, could your 1/ squash your commits and 2/ rebase on top of master? Thanks
