### ISSUE TITLE
Add a comment on an action in audit log

### ISSUE THREAD

**Issue by coudot** [ltb-project/service-desk#127]
The need is to be able to enter a comment when doing an action like locking an account.

This comment will be stored in audit log.

**Comment by coudot** [comment]
Targeted actions for the moment:
* Lock/Unlock account
* Block/Unblock (see #125)

My idea is to open a modal when cliking on the action button. The modal will display a comment textarea. Submitting it will do the action and save the comment in audit log.

See https://getbootstrap.com/docs/5.3/components/modal/

Requires #129 to have a recent bootstrap version

**Comment by coudot** [comment]
See with Abhishek

**Comment by davidcoutadeur** [comment]
TODO:

- [ ] add the possibility to trigger comment from everywhere. Currently, the lock/unlock and enable/disable comments are not asked in the menu listing all locked accounts nor in the menu listing all disabled accounts
- [ ] add doc for corresponding configuration parameters
- [ ] sometimes the audit log interface is slow. Investigate why
