### ISSUE TITLE
The page does not work on Nginx

### ISSUE THREAD

**Issue by aitemat** [ltb-project/service-desk#14]
Hi @all,
I have set up the page on Nginx but it doesn't seem to work.
Maybe the problem is Smarty. Can anybody help me answer?

**Comment by coudot** [comment]
Try to set debug mode and provide some logs

**Comment by coudot** [comment]
See https://docs.nginx.com/nginx/admin-guide/monitoring/logging/

**Comment by aitemat** [comment]
If using Nginx do we need Smarty config? I have configured the link below and installed as the link below: https://service-desk.readthedocs.io/en/stable/installation.html

**Comment by coudot** [comment]
You need Smarty to run Service Desk. This has nothing to do with Apache or Nginx, which are web servers.

**Comment by aitemat** [comment]
I had install smarty (version 3) but it hadn't location as on a document. 
On document: /usr/share/php/smarty3/Smarty.class.php
Mine is : /usr/share/php/Smarty/Smarty.class.php.
I wonder if it will affect the result?

**Comment by coudot** [comment]
As written in the doc, you must configure the path to your Smarty installation: https://service-desk.readthedocs.io/en/stable/general-parameters.html#smarty
