### ISSUE TITLE
Update to smarty4

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/service-desk#158]
This issue is a reminder to update to smarty4 when it will be available for all platforms.

I think it is interesting to now consider the upgrade to smarty4, for multiple reasons:
- smarty4 is released since 2021. It is now considered as the stable version. smarty3 is now only recommended for applications requiring PHP < 7.1 
- smarty4 seems well-packaged on multiple systems (tested and working on debian 12)
- we could simplify installation process by simply enabling smarty4 as a requirement in rpm/deb packages

For now (2024-07-31):
- smarty4 is not available on debian 11 and debian 10
- smarty4 is not available on EPEL/Fedora

The only thing I propose for now is to adapt dependency in debian packaging: smarty4|smarty3 (with a preference for smarty4)

**Comment by coudot** [comment]
@davidcoutadeur can we close this one?

**Comment by davidcoutadeur** [comment]
Yes, all the modifications applied in commit 6fbbacb, referenced by issue #142
