### ISSUE TITLE
Append option to sort login history in descending order

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#171]
Failed logins are displayed in ascending order.
Could be interresting to display the last failed login in first place...

![image](https://github.com/user-attachments/assets/488e22ee-bc39-4806-8e79-8c5ba8fec676)

**Comment by davidcoutadeur** [comment]
Agreed, and I don't think it's hard to code.

I'll give a look.

**Comment by coudot** [comment]
Not so simple because we pass all values as they are returned by the directory, for any attributes. This evolution would require to apply a specific code on an attribute, or maybe on an attribute type (date and ad_date).

**Comment by davidcoutadeur** [comment]
@cmaudoux could you test my last PR and tell me if it solves your issue? https://github.com/ltb-project/service-desk/pull/181

Drawbacks to discuss:
- sorting can be different according to the type of attribute
- hypothesis: for the PR to work, the attribute key of attributes_map hashmap should be the same as the attribute name.

**Comment by davidcoutadeur** [comment]
The different types are these ones:
- ad_date
- address
- bytes
- date
- dn_link
- mailto
- ppolicy_dn
- tel
- text

Except for bytes, the asort / arsort functions seem adapted. So I think we can keep the current behavior.
