### ISSUE TITLE
service-desk on centos 7 only display one pic

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/service-desk#23]
on centos 7  install by yum

service-desk only display one pic
[https://imgchr.com/i/0rVfCn](url)

![4](https://user-images.githubusercontent.com/5058391/95598436-7f23a200-0a82-11eb-9f02-5098d4ca4d53.png)

**Comment by coudot** [comment]
Yes. Search for an account in top right menu.

**Comment by ilanni2460** [comment]
@coudot i search  find this is  report :
HTTP ERROR 500
![1](https://user-images.githubusercontent.com/5058391/95597119-d3c61d80-0a80-11eb-8919-91443e152f6b.png)

service-desk debug logs:

![2](https://user-images.githubusercontent.com/5058391/95597174-e17ba300-0a80-11eb-9263-625ac063cf52.png)




service-desk config :
![3](https://user-images.githubusercontent.com/5058391/95597247-f5bfa000-0a80-11eb-95b2-82f423d7ab2d.png)

**Comment by coudot** [comment]
Please check that PHP LDAP is installed and module loaded.

**Comment by ilanni2460** [comment]
@coudot yes  i  have check the php ldap .and by phpinfo the php ldap module  have by loaded
![0](https://user-images.githubusercontent.com/5058391/95647293-d5cfc100-0b00-11eb-9868-79ab8ad2424a.png)

**Comment by ilanni2460** [comment]
@coudot this is all phpinfo

[https://imgchr.com/i/0yiRaj](url)

**Comment by ilanni2460** [comment]
this is apache config
[https://imgchr.com/i/0yiTMT](url)

**Comment by coudot** [comment]
You are runinng PHP 5.4 which is too old.

ldap_escape is available since PHP 5.6: https://www.php.net/manual/fr/function.ldap-escape.php

Try https://rpms.remirepo.net/

This is indeed an issue as we are providing RPMs for CentOS 7

**Comment by ilanni2460** [comment]
@coudot ok，tks   ，  i will  test php5.6 on centos7

**Comment by ilanni2460** [comment]
@coudot i  have the problem  by install php 7.0

tks
