### ISSUE TITLE
The account password has expired, but the web interface does not show that the password has expired

### ISSUE THREAD

**Issue by ilanni2460** [ltb-project/service-desk#25]
The account password has expired, but the web interface does not show that the password has expired
![0](https://user-images.githubusercontent.com/5058391/95843764-a7f5b100-0d7a-11eb-906a-1decd73082af.png)

**Comment by coudot** [comment]
If the password is already expired, you should have a warning on the page.

We don't display expiration date, see #19

**Comment by ilanni2460** [comment]
@coudot I mean, it didn't show the password expired, like this picture:
![Uploading 1.png…]()

**Comment by coudot** [comment]
What is the pwdMaxAge of your ppolicy?

**Comment by ilanni2460** [comment]
pwdMaxAge is 7776000 , 90d

**Comment by ilanni2460** [comment]
the account is expired 2020.9.27

**Comment by coudot** [comment]
Check that this account is not linked to another ppolicy, or that the pwdMaxAge is well defined in the default ppolicy

**Comment by ilanni2460** [comment]
@coudot this is ldap config ppolicy :
![0](https://user-images.githubusercontent.com/5058391/95875712-e6a06100-0da4-11eb-9cc9-7c6064b98709.png)

this ppolicy  account :

![1](https://user-images.githubusercontent.com/5058391/95875791-ff107b80-0da4-11eb-94ff-a73f8325b82b.png)


From the above two pictures, it can be clearly seen that the password policy is effective. And this password policy, we have been using it.
So I guess it’s because there is a problem in the code about whether the user password has expired

**Comment by ilanni2460** [comment]
@coudot I have checked the ldap service and did not find any error information for the account, but I found such a line in the error log of the service-desk, but I don’t think it will be affected

![2](https://user-images.githubusercontent.com/5058391/95879667-2ff2af80-0da9-11eb-8284-3ed2a4e06a46.png)

**Comment by ilanni2460** [comment]
@coudot I thought of a way to put
 $pwdMaxAge
 $pwdChangedTime
$changedDate
$expirationDate

Print out the values ​​of these variables to see

But i don't know how to print

**Comment by coudot** [comment]
You can use "error_log" in the code to print them in logs

**Comment by ilanni2460** [comment]
@coudot  ok i try ,tks

**Comment by ilanni2460** [comment]
@coudot Sure enough, it is caused by no permission, you are too awesome

very tks 
![4](https://user-images.githubusercontent.com/5058391/95882167-f5d6dd00-0dab-11eb-9f1d-22a64a7c5412.png)
