### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by madmath03** [ltb-project/service-desk#31]
Having an official Docker container for this would be pretty nice.

I can provide a PR for that, with docker-compose.

**Comment by coudot** [comment]
Hello @madmath03 

we have a Dockerfile for Self Service Password, maybe we can use the same approach for Service Desk and White Pages

See https://github.com/ltb-project/self-service-password/blob/master/Dockerfile

**Comment by madmath03** [comment]
Sure @coudot, though I was thinking of providing something a bit different since I believe Self Service Password Dockerfile could be improved as well 😅

**Comment by coudot** [comment]
You can propose a PR, we'll then discuss on it

**Comment by NoxInmortus** [comment]
Hello, you can check this one out if it fits you : https://github.com/NoxInmortus/docker-ldap-tool-box

**Comment by coudot** [comment]
Official Docker image now available at https://hub.docker.com/r/ltbproject/service-desk
