### ISSUE TITLE
userAccountControl

### ISSUE THREAD

**Issue by faust64** [ltb-project/service-desk#48]
As initially discussed here: https://github.com/ltb-project/self-service-password/issues/569
We may want to improve AD support, which may involve more than pwdAccountLockedTimes.

See:
 - https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties#list-of-property-flags
 - https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties
 - https://docs.microsoft.com/en-us/windows/win32/adschema/a-msds-useraccountdisabled

**Comment by coudot** [comment]
Service Desk is for now only for standard LDAP server, we need to adapt a lot of code for AD, not just UAC attribute

**Comment by coudot** [comment]
Will be fixed with #52
