### ISSUE TITLE
Fresh installation - Cannot access Service Desk 

### ISSUE THREAD

**Issue by radasys** [ltb-project/service-desk#67]
Hi! We have installed Service Desk in Ubuntu 22.04 using Debian/Ubuntu packages.

After the package and dependencies installation, we enabled the site (using a2ensite service-desk.conf). Then, we receive an error 500 message.

Access messages are logged in sd_access.log but nothing is logged in sd_error.log.

Could you give us further assistance?

Thank you!

**Comment by coudot** [comment]
There is a known issue with PHP 8 : https://github.com/ltb-project/service-desk/issues/55

There is another known issue with Smarty on Ubuntu : https://github.com/ltb-project/self-service-password/issues/681

**Comment by radasys** [comment]
Oh, my mistake. Sorry. Thank you for your fine support @coudot! I will implement workarounds mentioned in the posts.
