### ISSUE TITLE
Log who has done the action (audit trail)

### ISSUE THREAD

**Issue by coudot** [ltb-project/service-desk#72]
For now, access to Service Desk is anonymous, even if we recommend to add authentication (Web Server or SSO).

We should be able to get the identity of connected user and log every action done.

**Comment by coudot** [comment]
See also discussions in #21

**Comment by coudot** [comment]
Duplicate of #41

**Comment by artlog** [comment]
Taking a look

**Comment by coudot** [comment]
Hello @artlog 

I would have seen an easier solution to begin: use the admin name in the logs (with `error_log` -> https://www.php.net/manual/fr/function.error-log.php)

**Comment by coudot** [comment]
After discussions with several people, storing JSON in an audit file is a correct solution.

I will propose something slightly different that the format used in commit https://github.com/ltb-project/service-desk/commit/cec27ba65df633516347e43acdc3223df6b90d5a
