### ISSUE TITLE
Send a mail to administrator 

### ISSUE THREAD

**Issue by coudot** [ltb-project/service-desk#73]
Linked to #71 and #72 

If administrator identity is known, send a mail to confirm the action has been done. It will be a configuration option of course.

**Comment by artlog** [comment]
I propose a  $notify_admin_by_mail containing the mail to be notified.
For sake of simplicity it is better to have only one mail.
If multiple people need to be contacted , then a common mail for all should be used.
This can help admin team to know if pending client request was fulfilled.

When $notify_admin_by_mail is set any successful password change will be notified to this mail.
list of additional actions to cover could be done in a second step.

What should we include in this mail ? any additional information we can gather about web client ?

**Comment by cmaudoux** [comment]
Hello,

The idea is to send an email to the admin who resets the password. By admin I mean the user using the service desk. Admin's email can be retrieved from an HTTP header that can be defined like multi tenancy param.

Email body could be an external file where some specific variables like __PASSWD__ or __USER__ should be replaced.

**Comment by cmaudoux** [comment]
I agree with @coudot 

Cheers

**Comment by artlog** [comment]
working on it.

**Comment by cmaudoux** [comment]
Thanks
