### ISSUE TITLE
Avoid browsers prompting for storing new password

### ISSUE THREAD

**Issue by cmaudoux** [ltb-project/service-desk#74]
Admin reset user's password.

Browser proposes to store new password.

 Maybe use text input type text instead of input type password  and obfuscate by using JS.

**Comment by coudot** [comment]
I am not very enthusiast of using a text input field.

The best practice is to use the autocomplete property with "new-password" value, see https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by coudot** [comment]
@cmaudoux I found this solution: https://github.com/ltb-project/service-desk/pull/83/commits/cc34eac134f64ca808a442b56f470023da3a63fb

Works for me on Chrome and Firefox

Need to work more on the code to add a configuration option to switch from a standard password field to a text field with hidden characters.
