### ISSUE TITLE
Audit | User who has done the action is not logged

### ISSUE THREAD

**Issue by radasys** [ltb-project/service-desk#93]
Hi!

I'm testing Service Desk 0.5, you made a wonderful job! Thank you!

I have set up LDAP authentication in Apache configuration and enabled the Audit function. Although I can perform password reset and lock/unlock accounts, I have noticed that the logged message in /var/log/service-desk/audit.log does not include the username who made the change. It's logged as "anonymous":

`
{"date":"Wed, 26 Apr 2023 09:50:03","user_dn":"uid=user,ou=Users,dc=example,dc=com","done_by":"anonymous","action":"resetpassword","result":"passwordchanged"}
`

Thank you for your support!

**Comment by coudot** [comment]
Hello @radasys is it working for you?

**Comment by radasys** [comment]
Hi @coudot! 

I have just made it work slightly changing the directive to:

`RequestHeader set Auth-User expr=%{REMOTE_USER}`

I'm using Apache/2.4.52 in Ubuntu 22.04.2.

Thank you for your assistance and support!
