### ISSUE TITLE
update authTimestamp to pwdLastSuccess

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/service-desk#97]
In new openldap lastbind feature, authTimestamp is replaced by pwdLastSuccess.

We could make pwdLastSuccess attribute customizable in service-desk, and set "pwdLastSuccess" value by default

**Comment by coudot** [comment]
See #57

**Comment by coudot** [comment]
No need to customize the attribute, we will provide both definition, only the one active will be displayed

**Comment by coudot** [comment]
After some tests, we indeed need to define which attribute to use, else the idle account dashboard is not working.
